(lang dune 1.11)
(generate_opam_files true)
(package
 (name dose-common)
 (depends
  (dune (and :build (>= 1.11)))
  (cppo (and :build (>= 1.6.6)))
  (extlib (>= 1.7.6))
  (camlbz2 (>= 0.6.0))
  (camlzip (>= 1.08))
 )
)
